Repository graasp/graasp-plugin-chatbox, pull requests merged in 2023-03, with the labels that each got.

#48 feat: bump dependencies, upgrade websockets
  package.json
  src/chat/handler/chat-action-handler.test.ts
  src/chat/tasks/delete-message-task.ts
  src/chat/ws/hooks.ts
  src/mentions/ws/hooks.ts
  src/publicPlugin.ts
  yarn.lock
Labels: feature

#49 ci: add release-please workflow
  .github/workflows/auto-tag.yml
  .github/workflows/release-please-package.yml
Labels: chore, ci

#52 fix: rename package and author
  .github/workflows/test.yml
  package.json
  yarn.lock
Labels: chore
